// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exam.Models;

public partial class Good
{
    public int Id { get; set; }

    public string Article { get; set; }

    public string Name { get; set; }

    public string Mesurement { get; set; }

    public int? Price { get; set; }

    public string Provider { get; set; }

    public string Manufacturer { get; set; }

    public string Category { get; set; }

    public int? Discount { get; set; }

    public int? Amount { get; set; }

    public string Description { get; set; }

    public string Photo { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}